### ISSUE TITLE
questions abou acc

### ISSUE THREAD

**Issue by haoren55555** [jcy132/Hneg_SRC#2]
Sorry to bother, I used your pretrained seg models and cut models to test, but I found the acc pixAcc of cityscapes was 83.2, much larger than that of in the paper.
Did I do thing s wrong?

**Comment by jcy132** [comment]
We evaluate the scores based on the Official implementation of GcGAN [https://github.com/hufu6371/GcGAN]. Following the code, the pixel accuracy of pretrained model CUT outputs 70.263. Maybe there would be the bug in your evaluation code. As for the request, we will upload the code to get the scores.

**Comment by haoren55555** [comment]
thanks, I just looked the code in GcGAN, and it was nearly the same as drn which I used to compute the scores.
waiting for your code.
