### ISSUE TITLE
supplementary material

### ISSUE THREAD

**Issue by Yshouang** [jcy132/Hneg_SRC#4]
Dear author, where can I get the supplementary materials mentioned in your question?

**Comment by cyclomon** [comment]
Hi, Please refer to this link.
[https://openaccess.thecvf.com/content/CVPR2022/supplemental/Jung_Exploring_Patch-Wise_Semantic_CVPR_2022_supplemental.pdf](https://openaccess.thecvf.com/content/CVPR2022/supplemental/Jung_Exploring_Patch-Wise_Semantic_CVPR_2022_supplemental.pdf)

**Comment by jcy132** [comment]
Please refer the Code in https://github.com/Junya-Chen/FlatCLR . Decoupled infoNCE(DCE) loss has same form of FlatNCE.
